# Generated by Django 5.2.4 on 2025-07-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_to_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=20)),
                ('age', models.IntegerField()),
                ('job_description', models.TextField(max_length=50)),
            ],
        ),
    ]
