# Generated by Django 5.2.4 on 2025-07-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_careersquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='product_quantity',
        ),
    ]
